from enum import Enum


class Code(Enum):
    ACCESS_ALLOWED = 0,
    ACCESS_NOT_FOUND_VEHICLE = 1,
    ACCESS_OUT_OF_HOUR = 2,
    ACCESS_WITH_CAMERA_OUT_OF_HOUR = 3,

    OPEN_NORMAL = 4,
    OPEN_ABNORMAL = 5,
    CLOSE_NORMAL = 6,
    CLOSE_ABNORMAL = 7,
