"""AddedNewTableCamera

Revision ID: 4d474aa34ef5
Revises: b0ebac093d25
Create Date: 2024-03-05 21:02:28.830658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d474aa34ef5'
down_revision: Union[str, None] = 'b0ebac093d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('camera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=10), nullable=False),
    sa.Column('user', sa.String(length=10), nullable=False),
    sa.Column('manufacturer', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('camera')
    # ### end Alembic commands ###
