"""AddedColumnSentToServer

Revision ID: 6a3bef110e08
Revises: c1b23764b7dc
Create Date: 2024-03-19 19:51:34.890253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a3bef110e08'
down_revision: Union[str, None] = 'c1b23764b7dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('sent_to_server', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'sent_to_server')
    # ### end Alembic commands ###
