"""DeletedModelFromVehicle

Revision ID: 776875aa9a7d
Revises: 4d474aa34ef5
Create Date: 2024-03-10 17:38:31.456134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '776875aa9a7d'
down_revision: Union[str, None] = '4d474aa34ef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('model', mysql.VARCHAR(length=20), nullable=True))
    # ### end Alembic commands ###
