"""AddedColumnController

Revision ID: 7df2e74fd278
Revises: 6aace3b16eae
Create Date: 2024-04-23 20:48:07.401105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7df2e74fd278'
down_revision: Union[str, None] = '6aace3b16eae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera', sa.Column('controller', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('camera', 'controller')
    # ### end Alembic commands ###
