"""AddedColumnPlateAndOthersBaseColumnsInVehicle

Revision ID: b0ebac093d25
Revises: fc72f9529c73
Create Date: 2024-02-18 19:35:56.475860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0ebac093d25'
down_revision: Union[str, None] = 'fc72f9529c73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('vehicle', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('vehicle', sa.Column('plate', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle', 'plate')
    op.drop_column('vehicle', 'updated_at')
    op.drop_column('vehicle', 'created_at')
    # ### end Alembic commands ###
